logging: False
dataset_path: data/training.csv
output_dir: models/
model_name: fraud_detector_v1
epochs: 25
batch_size: 64
learning_rate: 0.001
optimizer: adam
shuffle: true
validation_split: 0.2
early_stopping:
  enabled: true
  patience: 5
